## ****************************************************************************
##
##  Makefile.config --
##
##  Original Author: Philipp A. Hartmann, OFFIS 
##  Modified by Reinier Torres for ECE-423 (Winter 2021)
##
## ***************************************************************************

## guess config from environment

## Variable that points to SystemC installation path
## Change <userid> in line below to match your user name
SYSTEMC_HOME?=/home/<userid>/ece423-labs/schedule/systemc-2.3.3
## Select the target architecture
TARGET_ARCH = linux64

## Select the architecture suffix, if necessary
ARCH_SUFFIX = -$(TARGET_ARCH)

## How to instruct the dynamic linker to locate the SystemC library
#LDFLAG_RPATH = -Wl,-rpath=

# default compiler flags
FLAGS_COMMON = -g -Wall
FLAGS_STRICT = -pedantic -Wno-long-long
FLAGS_WERROR = -Werror

# combined flags
#SYSTEMC_CXXFLAGS = $(FLAGS_COMMON) $(FLAGS_STRICT) $(FLAGS_WERROR)

# Additional preprocessor symbols
#SYSTEMC_DEFINES =

# Explicit location of the SystemC headers
#SYSTEMC_INC_DIR = $(SYSTEMC_HOME)/include

# Explicit location if the SystenC library
#SYSTEMC_LIB_DIR = $(SYSTEMC_HOME)/lib$(ARCH_SUFFIX)

# Run with valgrind
#VALGRIND=valgrind --log-file-exactly=valgrind.log
